### ISSUE TITLE
[Issue] Ore Processing Upgrade isn't working at first.

### ISSUE THREAD

**Issue by TorinnTheDragon** [Cazadorsniper/Furnace-Overhaul#1]
When I put a Ore Processing Upgrade in the furnace the first ore it smelts only gives me one, then after that it works as suppose to.

**Comment by Cazadorsniper** [comment]
I know, PO3 takes priority though.

**Comment by zzBuilderzz** [comment]
I can confirm WillBoy20101's findings. I also have this to add: the fuel efficiency upgrade works better than double efficiency. I was able to smelt 16 pieces of ore in an iron furnace with one piece of coal and have some burn ticks left over.

**Comment by zzBuilderzz** [comment]
btw what is PO3?

**Comment by Cazadorsniper** [comment]
@zzBuilderzz I was aware of ore processing issue before i updated see changelog : https://minecraft.curseforge.com/projects/furnace-overhaul/files/2528573

You have extra because the iron furnace is slightly faster than the vanilla furnace, efficiency upgrade still only doubles burn times.

PO3 is Project Ozone 3

**Comment by zzBuilderzz** [comment]
ah ok

**Comment by zzBuilderzz** [comment]
Approximately how many mods will PO3 have?

**Comment by Cazadorsniper** [comment]
This is fixed next update.
